import React from "react";
import ReactDOM from "react-dom";
import Button from "react-uikit-button";
import MuiThemeProvider from "material-ui/styles/MuiThemeProvider";
import { MuiDataTable } from "mui-data-table";

const data = [
  {
    "ORDERNUMBER": 10107,
    "QUANTITYORDERED": 30,
    "PRICEEACH": 95.7,
    "ORDERLINENUMBER": 2,
    "SALES": 2871,
    "ORDERDATE": "2/24/2003 0:00",
    "STATUS": "Shipped",
    "QTR_ID": 1,
    "MONTH_ID": 2,
    "YEAR_ID": 2003,
    "PRODUCTLINE": "Motorcycles",
    "MSRP": 95,
    "PRODUCTCODE": "S10_1678",
    "CUSTOMERNAME": "Land of Toys Inc.",
    "PHONE": "2125557818",
    "ADDRESSLINE1": "897 Long Airport Avenue",
    "ADDRESSLINE2": null,
    "CITY": "NYC",
    "STATE": "NY",
    "POSTALCODE": "10022",
    "COUNTRY": "USA",
    "TERRITORY": null,
    "CONTACTLASTNAME": "Yu",
    "CONTACTFIRSTNAME": "Kwai",
    "DEALSIZE": "Small"
},
{
    "ORDERNUMBER": 10121,
    "QUANTITYORDERED": 34,
    "PRICEEACH": 81.35,
    "ORDERLINENUMBER": 5,
    "SALES": 2765.9,
    "ORDERDATE": "5/7/2003 0:00",
    "STATUS": "Shipped",
    "QTR_ID": 2,
    "MONTH_ID": 5,
    "YEAR_ID": 2003,
    "PRODUCTLINE": "Motorcycles",
    "MSRP": 95,
    "PRODUCTCODE": "S10_1678",
    "CUSTOMERNAME": "Reims Collectables",
    "PHONE": "26.47.1555",
    "ADDRESSLINE1": "59 rue de l'Abbaye",
    "ADDRESSLINE2": null,
    "CITY": "Reims",
    "STATE": null,
    "POSTALCODE": "51100",
    "COUNTRY": "France",
    "TERRITORY": "EMEA",
    "CONTACTLASTNAME": "Henriot",
    "CONTACTFIRSTNAME": "Paul",
    "DEALSIZE": "Small"
},
{
    "ORDERNUMBER": 10134,
    "QUANTITYORDERED": 41,
    "PRICEEACH": 94.74,
    "ORDERLINENUMBER": 2,
    "SALES": 3884.34,
    "ORDERDATE": "7/1/2003 0:00",
    "STATUS": "Shipped",
    "QTR_ID": 3,
    "MONTH_ID": 7,
    "YEAR_ID": 2003,
    "PRODUCTLINE": "Motorcycles",
    "MSRP": 95,
    "PRODUCTCODE": "S10_1678",
    "CUSTOMERNAME": "Lyon Souveniers",
    "PHONE": "+33 1 46 62 7555",
    "ADDRESSLINE1": "27 rue du Colonel Pierre Avia",
    "ADDRESSLINE2": null,
    "CITY": "Paris",
    "STATE": null,
    "POSTALCODE": "75508",
    "COUNTRY": "France",
    "TERRITORY": "EMEA",
    "CONTACTLASTNAME": "Da Cunha",
    "CONTACTFIRSTNAME": "Daniel",
    "DEALSIZE": "Medium"
},
{
    "ORDERNUMBER": 10145,
    "QUANTITYORDERED": 45,
    "PRICEEACH": 83.26,
    "ORDERLINENUMBER": 6,
    "SALES": 3746.7,
    "ORDERDATE": "8/25/2003 0:00",
    "STATUS": "Shipped",
    "QTR_ID": 3,
    "MONTH_ID": 8,
    "YEAR_ID": 2003,
    "PRODUCTLINE": "Motorcycles",
    "MSRP": 95,
    "PRODUCTCODE": "S10_1678",
    "CUSTOMERNAME": "Toys4GrownUps.com",
    "PHONE": "6265557265",
    "ADDRESSLINE1": "78934 Hillside Dr.",
    "ADDRESSLINE2": null,
    "CITY": "Pasadena",
    "STATE": "CA",
    "POSTALCODE": "90003",
    "COUNTRY": "USA",
    "TERRITORY": null,
    "CONTACTLASTNAME": "Young",
    "CONTACTFIRSTNAME": "Julie",
    "DEALSIZE": "Medium"
},
{
    "ORDERNUMBER": 10159,
    "QUANTITYORDERED": 49,
    "PRICEEACH": 100,
    "ORDERLINENUMBER": 14,
    "SALES": 5205.27,
    "ORDERDATE": "10/10/2003 0:00",
    "STATUS": "Shipped",
    "QTR_ID": 4,
    "MONTH_ID": 10,
    "YEAR_ID": 2003,
    "PRODUCTLINE": "Motorcycles",
    "MSRP": 95,
    "PRODUCTCODE": "S10_1678",
    "CUSTOMERNAME": "Corporate Gift Ideas Co.",
    "PHONE": "6505551386",
    "ADDRESSLINE1": "7734 Strong St.",
    "ADDRESSLINE2": null,
    "CITY": "San Francisco",
    "STATE": "CA",
    "POSTALCODE": null,
    "COUNTRY": "USA",
    "TERRITORY": null,
    "CONTACTLASTNAME": "Brown",
    "CONTACTFIRSTNAME": "Julie",
    "DEALSIZE": "Medium"
},
{
    "ORDERNUMBER": 10168,
    "QUANTITYORDERED": 36,
    "PRICEEACH": 96.66,
    "ORDERLINENUMBER": 1,
    "SALES": 3479.76,
    "ORDERDATE": "10/28/2003 0:00",
    "STATUS": "Shipped",
    "QTR_ID": 4,
    "MONTH_ID": 10,
    "YEAR_ID": 2003,
    "PRODUCTLINE": "Motorcycles",
    "MSRP": 95,
    "PRODUCTCODE": "S10_1678",
    "CUSTOMERNAME": "Technics Stores Inc.",
    "PHONE": "6505556809",
    "ADDRESSLINE1": "9408 Furth Circle",
    "ADDRESSLINE2": null,
    "CITY": "Burlingame",
    "STATE": "CA",
    "POSTALCODE": "94217",
    "COUNTRY": "USA",
    "TERRITORY": null,
    "CONTACTLASTNAME": "Hirano",
    "CONTACTFIRSTNAME": "Juri",
    "DEALSIZE": "Medium"
},
{
    "ORDERNUMBER": 10180,
    "QUANTITYORDERED": 29,
    "PRICEEACH": 86.13,
    "ORDERLINENUMBER": 9,
    "SALES": 2497.77,
    "ORDERDATE": "11/11/2003 0:00",
    "STATUS": "Shipped",
    "QTR_ID": 4,
    "MONTH_ID": 11,
    "YEAR_ID": 2003,
    "PRODUCTLINE": "Motorcycles",
    "MSRP": 95,
    "PRODUCTCODE": "S10_1678",
    "CUSTOMERNAME": "Daedalus Designs Imports",
    "PHONE": "20.16.1555",
    "ADDRESSLINE1": "184, chausse de Tournai",
    "ADDRESSLINE2": null,
    "CITY": "Lille",
    "STATE": null,
    "POSTALCODE": "59000",
    "COUNTRY": "France",
    "TERRITORY": "EMEA",
    "CONTACTLASTNAME": "Rance",
    "CONTACTFIRSTNAME": "Martine",
    "DEALSIZE": "Small"
}
];
const VISIBLE_FIELDS = ['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES'];
const config = {
  paginated: false,
  search: "ORDERNUMBER",
  sortable:true,
  data: data,
   visibleFields: VISIBLE_FIELDS,
  columns: [
  
    { property: "ORDERNUMBER", title: "ORDERNUMBER" ,sortable: true,},
    { property: "QUANTITYORDERED", title: "QUANTITYORDERED" },
    { property: "PRICEEACH", title: "PRICEEACH" },
    { property: "ORDERLINENUMBER", title: "ORDERLINENUMBER" },
    { property: "SALES", title: "SALES" },
  ]
};

class App extends React.Component {
  render() {
    return (
      <MuiThemeProvider>
        <MuiDataTable config={config}  />
      </MuiThemeProvider>
    );
  }
}

ReactDOM.render(<App />, document.querySelector("#root"));
